// components/projects/SmartSpot.vue
<template>
    <article class="prose rounded-2xl bg-base-100 p-4 shadow-lg" id="smartspot">
        <h2>Smart Spot</h2>
        <figure>
            <figcaption>
                Unfortunately, there are no images or links available for this
                project.
            </figcaption>
        </figure>
        <p>
            Smart Spot was an Android application developed for the Inovaweek 2018
            event hosted by Vila Velha University. The application was
            specifically designed for internal use by students, teachers, and
            staff. Its features included real-time location tracking of teachers
            on campus, the ability to request support materials like erasers,
            pens, remote controls, etc., and a function to summon staff for minor
            repairs or adjustments to the equipment used in classes.
        </p>
        <p>
            The application was created in Android Studio by a team of 8 students.
            It functioned by facilitating the real-time exchange of data with an
            external server. The feature for tracking the position of teachers was
            implemented through Bluetooth beacons strategically installed in
            classrooms.
        </p>
        <h3>Tools</h3>
        <ul>
            <li>Adobe Photoshop</li>
        </ul>
        <h3>Contributors</h3>
        <ul>
            <li>
                <NuxtLink href="https://github.com/ArthurSegato">@ArthurSegato</NuxtLink>
            </li>
            <li>
                <NuxtLink href="https://github.com/dietermd">@dietermd</NuxtLink>
            </li>
            <li>
                <NuxtLink href="https://github.com/GMCoelho">@GMCoelho</NuxtLink>
            </li>
        </ul>
    </article>
</template>

// src/components/projects/smartspot.tsx
import { component$ } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";

export const SmartSpot = component$(() => {
  return (
    <>
      <article
        class="prose rounded-2xl bg-base-100 p-4 shadow-lg"
        id="smartspot"
      >
        <h2>Smart Spot</h2>
        <figure>
          <figcaption>
            Unfortunately, there are no images or links available for this
            project.
          </figcaption>
        </figure>
        <p>
          Smart Spot was an Android application developed for the Inovaweek 2018
          event hosted by Vila Velha University. The application was
          specifically designed for internal use by students, teachers, and
          staff. Its features included real-time location tracking of teachers
          on campus, the ability to request support materials like erasers,
          pens, remote controls, etc., and a function to summon staff for minor
          repairs or adjustments to the equipment used in classes.
        </p>
        <p>
          The application was created in Android Studio by a team of 8 students.
          It functioned by facilitating the real-time exchange of data with an
          external server. The feature for tracking the position of teachers was
          implemented through Bluetooth beacons strategically installed in
          classrooms.
        </p>
        <h3>Tools</h3>
        <ul>
          <li>Adobe Photoshop</li>
        </ul>
        <h3>Contributors</h3>
        <ul>
          <li>
            <Link href="https://github.com/ArthurSegato">@ArthurSegato</Link>
          </li>
          <li>
            <Link href="https://github.com/dietermd">@dietermd</Link>
          </li>
          <li>
            <Link href="https://github.com/GMCoelho">@GMCoelho</Link>
          </li>
        </ul>
      </article>
    </>
  );
});
